### PR TITLE
install with sphinx >1.7

### PR DESCRIPTION
**Pull request by suvarchal**
looks to fix this issue, #35,#50

Just removed `Directive` import from `sphinx.utils.compat` and imported `Directive` from `docutils.parsers.rst`.

### CODE REVIEW

**Comment by ceball** [comment]
Thanks for this PR. I want to merge it, but before I do, two things. One for you:
  * Do you know if your changes also work with earlier versions of sphinx (i.e. the 1.6 version we've been using so far), or do we now need to specify a new minimum version?

And one for me:
  * I need to restore nbsite's build process and tests. Right now nbsite's in an intermediate state, transitioning to a simpler system of testing and packaging. I'd really like to get the tests back before any more PRs are merged. I'll try to work on it tomorrow.

I am impressed that you are persevering :) Please feel free to ask questions as you go. Ironically the documentation of this project isn't very good yet...

**Comment by suvarchal** [comment]
Yes, it does with sphinx < 1.7.0 or specifically 1.6.7. 

:-).
Perseverance! comes from frustration trying to document from jupyter notebooks with widgets and under rtd theme. The simplest way with nbconvert doesnt come with widgets; didnt get much further with nbsite either.

**Comment by ceball** [comment]
> trying to document from jupyter notebooks with widgets

Which widget library are you referring to? ipywidgets? nbsite doesn't currently support ipywidgets (i.e. they won't appear, as you are finding with nbconvert). We do have a library that uses ipywidgets, but have so far only ever cheated to get widgets to appear in docs (e.g. follow the [doc/index.ipynb](http://nbviewer.jupyter.org/urls/notebooks.anaconda.org/cball/ioam-paramnb-index/download?version=) link from https://github.com/ioam/paramnb).

On sites generated with nbsite (e.g. geoviews.org, https://ioam.github.io/parambokeh, etc), if you've seen widgets, they are likely to have been holoviews and/or parambokeh widgets (which are supported by nbsite).

**Comment by suvarchal** [comment]
it is a mix of both ipywidgets and holoviews/parambokeh. But problem was clear with simplest of ipywidgets. Actually i was in bad luck and the main issue looks like version mismatches between jupyter-notebook/core, ipywidgets and nbwidgetextension and other plethora of dependencies. Otherwise could use nbsphinx extension; [ipywidgets](https://github.com/jupyter-widgets/ipywidgets/docs) on their [webpage](https://ipywidgets.readthedocs.io/en/latest/user_guide.html). BTW I do like your `sphinx_ioam_template`.

**Comment by suvarchal** [comment]
Thanks though! that was informative.

**Comment by ceball** [comment]
> BTW I do like your sphinx_ioam_template

If you're referring to the design, that's just stolen from bokeh: http://bokeh.pydata.org/en/latest/

> Actually i was in bad luck and the main issue looks like version mismatches between jupyter-notebook/core, ipywidgets and nbwidgetextension and other plethora of dependencies

I can only say that I too have also struggled with those issues. I have occasionally had working combinations, but not often enough to be able to use for doing work :(

**Comment by ceball** [comment]
(closed and re-opened to get a new PR build as there have been updates to master)

**Comment by ceball** [comment]
Thanks!

**Pull request merged**
