### PR TITLE
Always touch .jekyll file as part of build

### PR DESCRIPTION
**Pull request by jsignell**
This is a simplification that adds a --for-github flag to the build command. The first use is in https://github.com/pyviz/pyviz/pull/131

### CODE REVIEW

**Comment by jsignell** [comment]
I made this false by default to not break current behavior - but it will be true in all our cases, so might be better to have it be true.

**Comment by jbednar** [comment]
Can you explain what the intent is?  I can't quite get it.

**Comment by jsignell** [comment]
The intent is to get rid of this command in .travis.yml files: `touch ./builtdocs/.nojekyll # for github pages`.

See https://github.com/pyviz/pyviz/pull/131 for instance

**Comment by jsignell** [comment]
Probably not. Maybe I should add a don't touch that file flag instead. Would that be better?

**Comment by jbednar** [comment]
I still don't quite get it.  Yes, for github we need to have that file.  But does it hurt anything else?  Why not just always have it, and not need any flag to control it?  Unless it's problematic in some way, it seems distracting to have code for disabling it.

**Pull request merged**
