### PR TITLE
Updated import to use pyviz_comms

### PR DESCRIPTION
**Pull request by jlstevens**
Updates nbsite corresponding with the changes in https://github.com/ioam/holoviews/pull/2720

### CODE REVIEW

**Comment by jlstevens** [comment]
Note, this PR may not be ready to merge till ``pyviz_comms`` is available on the defaults channel.

**Comment by ceball** [comment]
If pyviz_comms is on pypi and pyviz (label/main and label/dev), I think that's enough; the instructions for a conda install are (or will be if they're not already) `conda install -c pyviz nbsite`.

**Comment by ceball** [comment]
Given my previous comment, is this ready to merge from your point of view?

From my point of view, same comment as on #52: I don't want to merge any more PRs until I restore the tests. Should be happening soon...

**Comment by jlstevens** [comment]
> Given my previous comment, is this ready to merge from your point of view?

I think so and I'm happy to wait till the tests are working again.

**Comment by ceball** [comment]
(closed and re-opened to get a new PR build as there have been updates to master)

**Pull request merged**
